Add some debugging docs
azimuth-cloud/capi-helm-charts pull request #419
Opened 2024-10-03 10:08 UTC by sd109

Closes #232

2024-10-03 10:12 UTC, sd109 commented on charts/openstack-cluster/DEBUGGING.md
> +```
I'm still on the fence about whether this diagram is really useful here, happy to remove it depending on others' opinions.

2024-10-04 13:41 UTC, mkjpryor requested changes
This is a good first crack.

I would maybe just be really explicit and add some examples of accessing the component logs. If you use the `deploy/<>` format, then it can be generic, e.g.:

```sh
kubectl -n capo-system logs deploy/capo-controller-manager`
```

or 

```sh
kubectl -n capi-addon-system logs deploy/cluster-api-addon-provider
```

2024-10-04 13:41 UTC, mkjpryor commented on README.md
> +See the openstack-cluster chart [README.md](./charts/openstack-cluster/README.md) for deployment instructions and [DEBUGGING.md](./charts/openstack-cluster/DEBUGGING.md) for debugging tips.
Don't know if this is required? I think linking the debugging page from the `openstack-cluster` README would be better?

2024-10-04 13:41 UTC, mkjpryor commented on charts/openstack-cluster/DEBUGGING.md
> +# Debugging
Maybe "Debugging a Cluster API cluster on OpenStack"?

2024-10-04 13:41 UTC, mkjpryor commented on charts/openstack-cluster/DEBUGGING.md
> +Now that the first control plane node has initialised successfully, the kubeconfig for the workload cluster will be written to a Kubernetes `Secret` named `<cluster-name>-kubeconfig` on the CAPI mana
This is slightly misleading maybe? The `kubeconfig` secret is actually generated once the API server address is known, which is usually once the LB is created and the FIP attached (if requested).

2024-10-04 13:41 UTC, mkjpryor commented on charts/openstack-cluster/DEBUGGING.md
> +kubectl --kubeconfig capi-mgmt get secret <cluster-name>-kubeconfig -o jsonpath='{.data.value}' | base64 -d > workload
The `go-template` format for `kubectl` supports a `base64decode` filter which I think is nicer than this:

```sh
kubectl --kubeconfig capi-mgmt get secret <cluster-name>-kubeconfig -o go-template='{{.data.value | base64decode}}' > workload
```

Not massively bothered either way though.

2024-10-10 13:04 UTC, mkjpryor approved these changes
LGTM

2024-10-10 13:04 UTC, merged